language: objective-c
compiler:
  - clang
  - gcc
before_install:
  - brew install clib
  - clib install
before_script:
  - make make_dir
script:
  - make tests/ns_bridge01
  - make tests/eval01
  - make tests/eval02
  - make tests/cond
  - make tests/scope
  - make tests/boolean
  - make tests/float
  - make tests/compare
  - make tests/list01
  - make tests/list02
  - make tests/hash_table01
  - make tests/hash_table02
  - make tests/lambda
  - make tests/regex
  - make tests/test01
  - make tests/test02
  - make tests/test03
  - make tests/test04
  - make tests/test05